image: sjstreeting/pipelines-hugo

pipelines:
  # Master branch deployment to live - no drafts
  branches:
    master:
      - step:
          script:
            - hugo
            - git subtree split --branch deploy --prefix public/