image: andthensome/alpine-hugo-git-bash

pipelines:
  # Master branch deployment to live - no drafts
  branches:
    master:
      - step:
          script:
            - git submodule update
            - hugo
            - git add . && git commit -m "new update" && git push
            - git filter-branch --subdirectory-filter public --state-branch deploy