image: andthensome/alpine-hugo-git-bash

pipelines:
  # Master branch deployment to live - no drafts
  branches:
    master:
      - step:
          script:
            - apk add openssh
            - git submodule update
            - hugo
            - git config user.name 'fhcflx'
            - git config user.email 'fhcflx@outlook.com'
            - git reset HEAD~8
            - git commit -am 'back to the future'
            - git push origin master
            - git filter-branch --prune-empty --subdirectory-filter public
            - git checkout -b deploy
            - git push origin deploy