image: hugomods/hugo

clone:
  depth: full

pipelines:
  # Master branch deployment to live - no drafts
  branches:
    master:
      - step:
          script:
            - apk update
            - apk add openssh
            - git fetch --unshallow || true
            - hugo
            - git config user.name 'Baldolino Calvino'
            - git config user.email 'alternate-silversurfer@outlook.com'
            - git add . && git commit -m 'new update'
            - git filter-branch --prune-empty --subdirectory-filter public
            - git checkout -b deploy
            - git push -f origin deploy
