baseURL = "https://alternate-silversurfer.bitbucket.io/"
theme = "cocoa-eh"
builddrafts = false
buildExpired = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
# languageCode = "pt-br"
DefaultContentLanguage = "en"
#title = "uma pagina livre"
disqusshortname = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
removePathAccents = true

[taxonomies]
# author = "authors"

[permalinks]
blog = "blog/:slug/"
posts = "posts/:slug/"

[params]
dateform = "2 Jan, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "a non blog"
copyright = "Copyright 2017-9 silversurfer, using theme Cocoa EH (with enhancements)"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "favicon.ico"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "github_id"
email = "alternate-silversurfer@outlook.com"
linkedin = "linkedin_id"
twitter = "altsilversurfer"
facebook = "facebook_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"

[languages]
  [languages.pt-br]
    title = "uma página livre"
    weight = 1
    languageName = "Português"
    [languages.pt-br.Params]
    description = "um não blog"
    LatestPosts = "Últimas postagens"
    seeMore = "Leia mais"

  [languages.dt]
    title = "jin seris ase"
    weight = 6
    languageName = "Dothraki"
    [languages.dt.Params]
    description = "jin vo sanase"
    LatestPosts = "Ha nakhaan sanase"
    seeMore = "Athtihar alikh"

  [languages.gn]
    title = "yepé sowa yurawa"
    weight = 5
    languageName = "Nheengatu"
    [languages.gn.Params]
    description = "yepé umbaá blog"
    LatestPosts = "Ana papera"
    seeMore = "Amú maã"

  [languages.zh]
    title = "一个自由页面"
    weight = 4
    languageName = "汉语"
    [languages.zh.Params]
    description = "一个没有博客"
    LatestPosts = "最新帖子"

  [languages.fr]
    title = "une page libère"
    weight = 3
    languageName = "Français"
    [languages.fr.Params]
    description = "un pas de blog"
    LatestPosts = "Derniers articles"
    seeMore = "En savoir plus"

  [languages.en]
    title = "a free page"
    weight = 2
    languageName = "English"
    [languages.en.Params]
    description = "a non blog"
    LatestPosts = "Latest posts"
    seeMore = "See more"

[markup]
    [markup.goldmark.parser.attribute]
      block = true
      title = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
