baseURL = "https://alternate-silversurfer.bitbucket.io/"
theme = "cocoa-eh"
builddrafts = false
buildExpired = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
#languageCode = "pt-br"
DefaultContentLanguage = "en"
#title = "uma pagina livre"
disqusshortname = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
removePathAccents = true

[taxonomies]
author = "authors"

[permalinks]
blog = "blog/:slug/"
posts = "posts/:slug/"

[params]
dateform = "2 Jan, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "a non blog"
copyright = "Copyright 2017-9 silversurfer, using theme Cocoa EH (with enhancements)"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "favicon.ico"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "github_id"
email = "alternate-silversurfer@outlook.com"
linkedin = "linkedin_id"
twitter = "altsilversurfer"
facebook = "facebook_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"

[languages]
  [languages.pt-br]
    title = "uma pagina livre"
    weight = 2
#    contentDir = "content/portugues"
    languageName = "Português brasileiro"
    [languages.pt-br.Params]
    description = "um não blog"
    [languages.pt-br.Taxonomies]
      "opinions" = "opiniões"
      "posts" = "postagens"
      "author" = "autores"
    [[languages.pt-br.menu.main]]
      url    = "/"
      name   = "Inicial"
      weight = 0

  [languages.dt]
    title = "jin seris ase"
    weight = 2
#    contentDir = "content/dothraki"
    languageName = "Dothraki"
    [languages.dt.Params]
    description = "jin vo sanase"
    [languages.dt.Taxonomies]
      "opinions" = "dirge"
      "posts" = "sanase"
    [[languages.dt.menu.main]]
      url    = "/"
      name   = "Home"
      weight = 0


  [languages.gn]
    title = "yepé sowa yurawa"
    weight = 2
#    contentDir = "content/nheengatu"
    languageName = "Nheengatu"
    [languages.gn.Params]
    description = "yepé manarau blog"
    [languages.gn.Taxonomies]
      "opinions" = "nemokõ"
      "posts" = "xu'ukã"
    [[languages.gn.menu.main]]
      url    = "/"
      name   = "yupirungawa"
      weight = 0

  [languages.zh]
    title = "一个自由页面"
    weight = 2
  #  contentDir = "content/dothraki"
    languageName = "汉语"
    [languages.zh.Params]
    description = "一个没有博客"
    [languages.zh.Taxonomies]
      "opinions" = "意见"
      "posts" = "帖子"
    [[languages.zh.menu.main]]
      url    = "/"
      name   = "主页"
      weight = 0

    [languages.fr]
      title = "une page libère"
      weight = 2
    #  contentDir = "content/dothraki"
      languageName = "Français"
      [languages.fr.Params]
      description = "un pas de blog"
      [languages.fr.Taxonomies]
        "opinions" = "des avis"
        "posts" = "des postes"
      [[languages.fr.menu.main]]
        url    = "/"
        name   = "page d'accueil"
        weight = 0

  [languages.en]
    title = "a free page"
    weight = 2
#    contentDir = "content/english"
    languageName = "English"
    [languages.en.Params]
    description = "a non blog"
#    [languages.en.Taxonomies]
#      "opiniões" = "opinions"
#      "postagens" = "posts"
    [[languages.en.menu.main]]
      url    = "/"
      name   = "Home"
      weight = 0

[markup]
    [markup.goldmark.parser.attribute]
      block = true
      title = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
