baseURL = "/"
theme = "cocoa-eh"
builddrafts = false
buildExpired = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
#languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
#title = "uma pagina livre"
#author = "silversurfer"
disqusshortname = ""
pluralizelisttitles = false
preserveTaxonomyNames = true
removePathAccents = true

[taxonomies]
author = "authors"

[permalinks]
blog = "blog/:slug/"
postagens = "postagens/:slug/"

[params]
dateform = "2 Jan, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "um n�o blog"
copyright = "Copyright 2017 silversurfer, using theme Cocoa EH (with enhancements)"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "favicon.ico"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "github_id"
email = "alternate-silversurfer@outlook.com"
linkedin = "linkedin_id"
twitter = "altsilversurfer"
facebook = "facebook_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"

[languages]
  [languages.pt-br]
    title = "uma pagina livre"
    weight = 1
#    contentDir = "content/portugues"
    languageName = "Português brasileiro"
    [[languages.pt-br.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 0

  [languages.dt]
    title = "jin seris ase"
    weight = 2
#    contentDir = "content/dothraki"
    languageName = "Dothraki"
    [languages.dt.Taxonomies]
      "opiniões" = "serisi"
    [[languages.en.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 0
